### PR TITLE
US228 - Adding more request options.

### PR DESCRIPTION
**Pull request by jsdevel**
* removeIeElements
* removeSharepointAttributes

Without these options: `view-source:http://localhost:3000/?commentOutScripts&standardizeClassNames`
```html

<!-- BeginContent -->
                        <div>

                            <div id="mainBody" class="content">
                                <div>
                                    <div id="notificationArea" class="ms-notif-box"></div>
                                    <div id="DeltaPageStatusBar">
	
                                        <div id="pageStatusBar"></div>
                                    
</div>
                                    <div id="divBreadcrumb" class="container" style="display:none"></div>
                                    <div id="DeltaPlaceHolderMain">
	
                                        <a id="mainContent" name="mainContent" tabindex="-1"></a>
                                        
<div class="home home-no-bottom-logo">

<div id="ContentSection1">
<div id="ctl00_PlaceHolderMain_ctl00_label" style='display:none'>ContentSection1</div><div id="ctl00_PlaceHolderMain_ctl00__ControlWrapper_RichHtmlField" class="ms-rtestate-field" style="display:inline" aria-labelledby="ctl00_PlaceHolderMain_ctl00_label"><div class="content"><div class="container intro"><h1 class="text-center">We’ll handle it from here.<sup>™</sup></h1>
                <a class="btn small-blue-btn" href="/request-services">Request Services</a>
            </div><div class="hero"></div></div></div>
</div>

<div id="ContentSection2">
<div id="ctl00_PlaceHolderMain_ctl01_label" style='display:none'>ContentSection2</div><div id="ctl00_PlaceHolderMain_ctl01__ControlWrapper_RichHtmlField" class="ms-rtestate-field" style="display:inline" aria-labelledby="ctl00_PlaceHolderMain_ctl01_label"></div>
</div>

<div id="ContentSection3">
<div id="ctl00_PlaceHolderMain_ctl02_label" style='display:none'>ContentSection3</div><div id="ctl00_PlaceHolderMain_ctl02__ControlWrapper_RichHtmlField" class="ms-rtestate-field" style="display:inline" aria-labelledby="ctl00_PlaceHolderMain_ctl02_label"></div>
</div>

<div id="ContentSection4">
<div id="ctl00_PlaceHolderMain_ctl03_label" style='display:none'>ContentSection4</div><div id="ctl00_PlaceHolderMain_ctl03__ControlWrapper_RichHtmlField" class="ms-rtestate-field" style="display:inline" aria-labelledby="ctl00_PlaceHolderMain_ctl03_label"></div>
</div>

<div id="ContentSection5">
<div id="ctl00_PlaceHolderMain_ctl04_label" style='display:none'>ContentSection5</div><div id="ctl00_PlaceHolderMain_ctl04__ControlWrapper_RichHtmlField" class="ms-rtestate-field" style="display:inline" aria-labelledby="ctl00_PlaceHolderMain_ctl04_label"></div>
</div>

<div id="ContentSection6">
<div id="ctl00_PlaceHolderMain_ctl05_label" style='display:none'>ContentSection6</div><div id="ctl00_PlaceHolderMain_ctl05__ControlWrapper_RichHtmlField" class="ms-rtestate-field" style="display:inline" aria-labelledby="ctl00_PlaceHolderMain_ctl05_label"></div>
</div>

</div>
<div style='display:none' id='hidZone'><menu class="ms-hide">
		<ie:menuitem id="MSOMenu_Help" iconsrc="/_layouts/15/images/HelpIcon.gif" onmenuclick="MSOWebPartPage_SetNewWindowLocation(MenuWebPart.getAttribute('helpLink'), MenuWebPart.getAttribute('helpMode'))" text="Help" type="option" style="display:none">

		</ie:menuitem>
	</menu></div>
                                    
</div>
                                </div>
                                <div id="DeltaFormDigest">
	
                                    
										<!--<script type="text/javascript">//<![CDATA[
        var formDigestElement = document.getElementsByName('__REQUESTDIGEST')[0];
        if (!((formDigestElement == null) || (formDigestElement.tagName.toLowerCase() != 'input') || (formDigestElement.type.toLowerCase() != 'hidden') ||
            (formDigestElement.value == null) || (formDigestElement.value.length <= 0)))
        {
            formDigestElement.value = '0xDD8815CBD579E1B4F0D66CE4864F18E56067DCBD2684F465A17634A4C58D17B2110E158A12FB6588B4347574738EBEAED959E76C9999244A80EB7F093A090266,21 Sep 2015 18:53:20 -0000';
            g_updateFormDigestPageLoaded = new Date();
        }
        //]]>
        </script>-->
                                    
                                
</div>
                            </div>


                        </div>
                        <!-- EndContent -->
```

With these options: `view-source:http://localhost:3000/?commentOutScripts&standardizeClassNames&removeIeElements&removeSharepointAttributes`

```html

<!-- BeginContent -->
                        <div>

                            <div id="mainBody" class="content">
                                <div>
                                    <div id="notificationArea" class="ms-notif-box"></div>
                                    <div id="DeltaPageStatusBar">
	
                                        <div id="pageStatusBar"></div>
                                    
</div>
                                    <div id="divBreadcrumb" class="container" style="display:none"></div>
                                    <div id="DeltaPlaceHolderMain">
	
                                        <a id="mainContent" name="mainContent" tabindex="-1"></a>
                                        
<div class="home home-no-bottom-logo">

<div id="ContentSection1">
<div  style='display:none'>ContentSection1</div><div  class="ms-rtestate-field" style="display:inline" ><div class="content"><div class="container intro"><h1 class="text-center">We’ll handle it from here.<sup>™</sup></h1>
                <a class="btn small-blue-btn" href="/request-services">Request Services</a>
            </div><div class="hero"></div></div></div>
</div>

<div id="ContentSection2">
<div  style='display:none'>ContentSection2</div><div  class="ms-rtestate-field" style="display:inline" ></div>
</div>

<div id="ContentSection3">
<div  style='display:none'>ContentSection3</div><div  class="ms-rtestate-field" style="display:inline" ></div>
</div>

<div id="ContentSection4">
<div  style='display:none'>ContentSection4</div><div  class="ms-rtestate-field" style="display:inline" ></div>
</div>

<div id="ContentSection5">
<div  style='display:none'>ContentSection5</div><div  class="ms-rtestate-field" style="display:inline" ></div>
</div>

<div id="ContentSection6">
<div  style='display:none'>ContentSection6</div><div  class="ms-rtestate-field" style="display:inline" ></div>
</div>

</div>
<div style='display:none' id='hidZone'><menu class="ms-hide">
		
	</menu></div>
                                    
</div>
                                </div>
                                <div id="DeltaFormDigest">
	
                                    
										<!--<script type="text/javascript">//<![CDATA[
        var formDigestElement = document.getElementsByName('__REQUESTDIGEST')[0];
        if (!((formDigestElement == null) || (formDigestElement.tagName.toLowerCase() != 'input') || (formDigestElement.type.toLowerCase() != 'hidden') ||
            (formDigestElement.value == null) || (formDigestElement.value.length <= 0)))
        {
            formDigestElement.value = '0x1E072C6E45F5D455318D07F617E44134706C55E0E8E1BDF9B75BF03E66DC4B4D0CAEEAB3414BBED38FB90F77AF1B58CAA0BB7133C0C49BFAEAFDA993BE36CA4D,21 Sep 2015 18:54:38 -0000';
            g_updateFormDigestPageLoaded = new Date();
        }
        //]]>
        </script>-->
                                    
                                
</div>
                            </div>


                        </div>
                        <!-- EndContent -->
```

### CODE REVIEW

**Comment by bkyarger** [comment]
Seems to me that anything that is tied to javascript that we have to convert we should probably remove the ids when we implement the JS.  Otherwise it'll be hard to find the element that is being manipulated when it's time to modify the JS.  A quick and dirty way of identifying them might be if ```style='display:none'``` is present.  Just my $.02.

**Comment by bkyarger** [comment]
:+1:  on the implementation - just not sure how much using removeSharepointAttributes makes sense.

**Comment by jsdevel** [comment]
Agreed on all counts.  Part of my work here was to analyze the markup output by sharepoint.  Looking at the output, it does seem we could add another option `removeEmptyContentSections`.  I have my doubts those are ever shown by javascript though.  I would bet they're just output by Sharepoint that way when the content is empty.

Doing some analysis to go through the JS to find the attributes used would likely be a good exercise to see if these options would ever be safe to use during the actual migration.

**Comment by srogers202** [comment]
:+1: Cool. Awesome way of automating this stuff.

**Pull request merged**
